/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FreightDto
 */
export interface FreightDto {
    /**
     * 
     * @type {number}
     * @memberof FreightDto
     */
    volume?: number;
    /**
     * 
     * @type {string}
     * @memberof FreightDto
     */
    start?: string;
    /**
     * 
     * @type {string}
     * @memberof FreightDto
     */
    destination?: string;
}

export function FreightDtoFromJSON(json: any): FreightDto {
    return FreightDtoFromJSONTyped(json, false);
}

export function FreightDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FreightDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'volume': !exists(json, 'volume') ? undefined : json['volume'],
        'start': !exists(json, 'start') ? undefined : json['start'],
        'destination': !exists(json, 'destination') ? undefined : json['destination'],
    };
}

export function FreightDtoToJSON(value?: FreightDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'volume': value.volume,
        'start': value.start,
        'destination': value.destination,
    };
}


